### ISSUE TITLE
Section: Loop Performance - Cache Array Length; global variable.

### ISSUE THREAD

**Issue by garrow** [taitems/Front-End-Development-Guidelines#14]
In this example `len` is in the (default) global scope.

```
for (var i = 0, len = toLoop.length; i < len; i++) {
    // GOOD - the length is only looked up once and then cached
}
```

This is a safer example.

```
for (var i = 0, var len = toLoop.length; i < len; i++) {
    // GOOD - the length is only looked up once and then cached
}
```

**Comment by ryansully** [comment]
Your second example is not even really that safe in terms of scope.

In JavaScript (before 1.7), there is no such thing as block scope.  Declaring a variable in a `for` loop with `var` will use the scope of its parent function or, in the absence any such containing function, the global scope.

JavaScript 1.7 introduced the `let` keyword for block scope to be used instead of `var`. Being a feature of JavaScript 1.7, the `let` keyword is not ready for general web use as of this time due to lack of support by some browsers, most notably IE.

**Comment by taitems** [comment]
The second example throws a JavaScript error, even if I "use strict";

**Comment by garrow** [comment]
Well, I feel stupid. Goes to show you should actually test bug reports before submitting them.

**Comment by taitems** [comment]
For clarity: http://jsfiddle.net/WuK5w/
