### ISSUE TITLE
W3C markup validation

### ISSUE THREAD

**Issue by ryansully** [taitems/Front-End-Development-Guidelines#19]
A page about front end development guidelines should probably pass W3C markup validation:
http://validator.w3.org/check?verbose=1&uri=http%3A%2F%2Ftaitems.github.com%2FFront-End-Development-Guidelines%2F

As of May 6:  48 Errors, 4 warning(s)

**Comment by exside** [comment]
=), some people really check valid markup on every page? Love this, then my hard work to write valid code makes sense =P!

The only 2 errors which are critical are 1) not declaring a charset (this should really be done) and 2) the one with the <p>-tag around line 900... the rest is related to the syntax highlighting and maybe not really worth the time fixing it...

**Comment by ryansully** [comment]
I personally consider it a matter of professionalism for a front-end developer to write valid semantic markup. It certainly plays a role in my decision when hiring for a front-end position. ;)

If you think there's a lot of work to do for validation and you're still interested in validating, you can patch from my forked commit here:
https://github.com/ryansully/Front-End-Development-Guidelines/commit/37c71a973bc86f0b36e31ed4c314444b03f3d5ef
(it's not worth submitting a pull req if the original author has no interest in valid markup)

**Comment by exside** [comment]
So do I =)

I had a look at the issues in that file and corrected them as far as I quickly could, the charset thing was easy...the <p> tag issue occurs because of the ul unside the p-tag i think...not so sure about that but seems valid to me (isn't a list allowed inside a paragraph because it's another block element?) when I look at the code and the whole bunch of wrong mime-type for script-node errors comes from the synthax-highlighter which depends on that type attribute. This is bad programming from the plugin writer but I think this can't be omitted when using this plugin whitout rewriting it^^...

and I don't think that we can speak the autor guilty of not being interested in valid code, so maybe he will pull the request =) and if not...site is helpful and working!

EDIT: OK, I see you have fixed a lot =), does the syntax-highlighting work with the pre-tags? Would be much nicer and more semantic! If I were you I would submit pull-request with your corrections, this was a lot of work! thanks for that

**Comment by ryansully** [comment]
Syntax highlighting works fine with pre tags; view my forked GH page for example:
http://ryansully.github.com/Front-End-Development-Guidelines/

I submitted a pull req if you want to extend the discussion there:
https://github.com/taitems/Front-End-Development-Guidelines/pull/29

**Comment by taitems** [comment]
Since recent revisions to the code base the whole site only has 3 errors which can be easily resolved.

Will hopefully fix in the coming days unless someone wants to submit a pull request?

**Comment by taitems** [comment]
Woops, forgot to mention I fixed this 4 days ago in commit 90730e609be4dfdbcead7f7d590ea855587aad43
